build:
	cd HelloWorld && make
	cd Generator && make
	cd string && make
	cd vector && make
	cd thread && make
	cd map && make
	cd mutex && make
	cd atomic && make
	cd memory_order && make
	cd unique_ptr && make
	cd sort && make
	cd duration && make
	cd enable_if && make
	cd exception_ptr && make
	cd exchange && make
	cd forward && make
	cd function && make
	cd invoke && make
	cd is_same && make
	cd condition_variable && make
	cd iterator_traits && make
	cd remove_cv && make
	cd unique_lock && make
	cd scoped_lock && make
	cd rand && make
	cd nullptr_t && make
	cd tuple && make
	cd allocator && make
	cd initializer_list && make
	cd limit && make

clean:
	cd HelloWorld && make clean
	cd Generator && make clean
	cd string && make clean
	cd vector && make clean
	cd thread && make clean
	cd map && make clean
	cd mutex && make clean
	cd atomic && make clean
	cd memory_order && make clean
	cd unique_ptr && make clean
	cd sort && make clean
	cd duration && make clean
	cd enable_if && make clean
	cd exception_ptr && make clean
	cd exchange && make clean
	cd forward && make clean
	cd function && make clean
	cd invoke && make clean
	cd is_same && make clean
	cd condition_variable && make clean
	cd iterator_traits && make clean
	cd remove_cv && make clean
	cd unique_lock && make clean
	cd scoped_lock && make clean
	cd rand && make clean
	cd nullptr_t && make clean
	cd tuple && make clean
	cd allocator && make clean
	cd initializer_list && make clean
	cd limit && make clean
