name: Performance for Pull Request

on:
  pull_request_target:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  benchmark:
    name: Performance regression check
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - name: Build benchmark
        run: |
           sudo apt install libaio-dev libgtest-dev -y
           cd /usr/src/gtest
           sudo mkdir build && cd build
           sudo cmake .. && sudo make
           sudo apt install libgmock-dev -y
           sudo apt install libbenchmark-dev -y
           cd ${{github.workspace}} && CXX=clang++ CC=clang cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
           cd ${{github.workspace}}/build/benchmarks && make -j
      - name: Run benchmark
        run: cd ${{github.workspace}}/build/benchmarks && ./benchmarking --benchmark_format=json | tee benchmarking.json
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: C++ Benchmark
          tool: 'googlecpp'
          output-file-path: ${{github.workspace}}/build/benchmarks/benchmarking.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-always: false
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '150%'
          fail-threshold: '200%'
          comment-on-alert: true
          auto-push: false
          gh-pages-branch: benchmark-monitoring
          benchmark-data-dir-path: benchmark-monitoring
