name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
    paths:
      - "docs/**"
      - ".github/workflows/static.yml"

  pull_request:
    paths:
      - "docs/**"
      - ".github/workflows/static.yml"

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install
        run: sudo apt-get install doxygen graphviz
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Yarn Install
        run: yarn install
        working-directory: ${{github.workspace}}
      - name: Build Website
        run: yarn docs:build
        working-directory: ${{github.workspace}}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: "docs/public"

  deploy:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
