name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, etc.)
  BUILD_TYPE: Release

jobs:
  build_with_cmake:
    runs-on: windows-latest

    strategy:
      matrix:
        mode: [ Release ]
        arch: [ x64 ]

    env:
      CXX: cl.exe
      CC: cl.exe

    steps:
      - uses: actions/checkout@v7

      - name: Generate Project
        run: cmake -B Build/${{ matrix.mode }} -DCMAKE_BUILD_TYPE=${{ matrix.mode }} -DRFK_DEV=1 -A ${{ matrix.arch }}

      - name: Build async_simple
        run: cmake --build Build/${{ matrix.mode }} --config ${{ matrix.mode }} --verbose

      - name: Test
        working-directory: ${{github.workspace}}/Build/${{ matrix.mode }}
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -C ${{ matrix.mode }} --output-on-failure

  build_with_bazel:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v7

      - name: Build 
        working-directory: ${{github.workspace}}
        # Lazy.bench.cpp intentionally instantiates a coroutine chain 1000 levels deep.
        run: bazel build --cxxopt=/templateDepth:2000 ...

      - name: Test
        working-directory: ${{github.workspace}}
        run: bazel test --cxxopt=/templateDepth:2000 --test_output=errors ...
